### ISSUE TITLE
segmentstem "Correcting stem" errors

### ISSUE THREAD

**Issue by jgrn307** [apburt/treeseg#10]
We found during our workflow an error in segmentstem that CAN occur during the "Correcting stem:" phase.  The error that occurs is:
...
----------: cluster_20.pcd
RANSAC cylinder fit: 0.2
Segmenting extended cylinder: cylinder_20.pcd
Segmenting ground returns: cylinder_noground_20.pcd
Euclidean clustering: 0.184679, cylinder_noground_clusters_20.pcd
Region-based segmentation: cylinder_noground_clusters_regions_20.pcd
Correcting stem: stem_20.pcd
----------: cluster_21.pcd
RANSAC cylinder fit: 0.2
Segmenting extended cylinder: cylinder_21.pcd
Segmenting ground returns: cylinder_noground_21.pcd
Euclidean clustering: 0.0493233, cylinder_noground_clusters_21.pcd
Region-based segmentation: cylinder_noground_clusters_regions_21.pcd
Correcting stem: terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!
Aborted (core dumped)

Note cluster_20 completed fine but 21 failed.

I have included the files to replicate this error as follows:
https://nevada.box.com/s/kfjqnbkzjyox0eygtstamuf4o5a50tfb

To repeat the workflow to get to this stage (note the pcd is already downsampled):
getdemslice 2 3 6 P002_E1_clip_downsample.pcd
findstems 15 0.2 2 P002_E1_clip_coords.dat P002.slice.downsample.pcd
segmentstem 12.5 P002_E1_clip_downsample.pcd cluster_*.pcd

I've played around with other slice/findstem parameters and this error frequently pops up, with different clusters.

**Comment by apburt** [comment]
segmentstem has changed a fair bit since v0.1.0, and several bugs have been caught along the way, so hopefully this is fixed now.
