### ISSUE TITLE
Need for help with starting analysis

### ISSUE THREAD

**Issue by ShukhratSh** [apburt/treeseg#12]
Hello,

I installed treeseg on Ubuntu and trying to use for plot based TLS point cloud. I have single return LAS files one hectare plot with 5 cm point spacing. It was classified into ground and non-ground points and georeferenced. I converted it into PCD file with CloudCompare to be able to use in treeseg. I need help with starting the segmentation, please. Volumne of my data is 324 mb. 
`findstems 15 0.2 2 /Documents/9a-4.pcd
Returns error: Reading slice: terminate called after throwing and instance of std::logic_error
Aborted (core dumped)`

`segmentcrown [14-16] Documents/19a-4.pcd Reading volume cloud: Segmentation fault (core dumped)`
I clipped small part of point cloud which is only 31 mb. 
`Reading volume cloud: [pcl::KdTreeFLANN::read] Could not find file ...
complete
Eucledian clustering: 0, [pcl::KdTreeFLANN;;setInputCloud] Cannot create a KDTree with an empty input cloud!
terminate called after throwing an instance of pcl::IOexception
what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data`

Could someone please help with starting?

Thanks so much in advance.

**Comment by apburt** [comment]
Hi,

A bit hard to diagnose what is going on here. I'd probably start with the PCD file- are you confident it is correctly formed? treeseg by default expects the input point cloud to be in PointXYZ format.

PCL itself comes with some tools to view point clouds, e.g., pcl_viewer

Cheers,

Andy

**Comment by Jaqen-H-ghar** [comment]
as you probably see it, the command "findstems" has 5 parameters:

findstems 5 0.2 2 ../FGC01_coords.dat ../FGC01.slice.pcd
