### ISSUE TITLE
unkowned number 

### ISSUE THREAD

**Issue by yangshikai1997** [apburt/treeseg#13]
getcrownvolume.cpp -> function  maxheight and maxcrown 
i can not understanding.
float maxheight(float dbh)
{
	//m    -> 41.22 * dbh ^ 0.3406
	//ci_u -> 42.30 * dbh ^ 0.3697
	float height = 42.30 * pow(dbh,0.3697) + 5;
	return height;
}

float maxcrown(float dbh)
{
	//m    -> 29.40 * dbh ^ 0.6524
	//ci_u -> 30.36 * dbh ^ 0.6931
	float extent = 30.36 * pow(dbh,0.6931) + 5; 
	return extent;
}

**Comment by apburt** [comment]
getcrownvolume is intended to pull out the point cloud of the crown of interest + any nearby vegetation. The dimensions of the box driving the passthrough filter are driven here by these allometries. If it is not giving the whole crowns of your trees, then you can increase them.
