### ISSUE TITLE
Rxp2pcd generating corrupt PCDs

### ISSUE THREAD

**Issue by tpet93** [apburt/treeseg#14]
Running rxp2pcd on Red Hat Linux I was gettting corrupt Pcd errors.
`[pcl::PCDReader::read] Corrupted PCD file. The file is smaller than expected!`
I believe I found the cause of the error in the line 82:

`int tile_pointcount[tile_count];`

Does not always initialize the point count for each tile to zero, 
and may overflow with many point per tile.

this causes a mismatch between the reported point-cloud size in the header and the size of the binary data.

It should be replaced with:

` unsigned long int tile_pointcount[tile_count] = { 0 };`

**Comment by apburt** [comment]
Nice catch! Thanks for picking this up & update has been pushed now.

So initialises as an array of zeros and using unsigned long will double the max PCD size to ~4.3B.
