### ISSUE TITLE
 How to use only .pcd format point cloud for segmentation

### ISSUE THREAD

**Issue by jiang-li1** [apburt/treeseg#16]
Our forestry scans rarely have .dat data, most of which are common data formats such as pcd. How to use your treeseg to directly split the data collected by pcd format forest radar? Thank you！

**Comment by tpet93** [comment]
I initially had some confusion about the input files.
Each .dat file is is just a text file containing ascii 4x4 transformation matrix's.
This is used to register several rxp scans(indivual tls scans in reigl's format).

I will try to summarize the behavior below

plotcoords creates a text file as such:
`-13.3903 45.2606 0 32.1628`
With the xmin,xmax, ymin,ymax limits of your plot.

rxp2pcd:
Generates N pcd tiles over the plot area.
Tiles are non overlapping and extend 10m beyond the plot limits

filenames in this format:
FGC01.tile.0.pcd`
FGC01.tile.1.pcd`
FGC01.tile.2.pcd`


Then you should be able to skip to this command:

`downsample 0.04 FGC01.tile.*.pcd`

Regards
Tony

**Comment by jiang-li1** [comment]
Should I edit the file FGC01.dat? I rename my PCD files FGC01.tile.2.pcd and downsample 0.04 FGC01.tile.*.pcd,and getdemslice 2 3 6 FGC01.tile.downsample.*.pcd,when findstems 15 0.2 2 ../FGC01_coords.dat ../FGC01.slice.pcd,it not work and show：

Reading slice: [pcl::PCDReader::read] Could not find file '../FGC01.slice.pcd'.
complete
Cluster extraction: [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!
Regards
Jiang Li

**Comment by jiang-li1** [comment]
I edit the file FGC01.dat and  run ./findstems 15 0.2 2 FGC01_coords.dat FGC01.slice.pcd,the shell show wrong with:
eading slice: complete
Cluster extraction: FGC01.intermediate.slice.clusters.pcd | 43
Region-based segmentation: FGC01.intermediate.slice.clusters.regions.pcd | 35
RANSAC cylinder fits: terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!

**Comment by apburt** [comment]
Yes so the documentation here is lacking (it is still on the to-do list!). See #4 for a bit more detail, but if you are not using riegl data and rxp2pcd, then yes you will need to put your lidar data into pcd format tiles (it can be just the 1 tile). The .dat and coord files are all specific to rxp2pcd, and not needed from downsample (or thin) onwards.

**Comment by tpet93** [comment]
@jiang-li1 your last error is occuring because the line 95:
 ```c
writeClouds(cyls,ss.str(),false);
```
Is trying to write a point-cloud of cylinders when no valid cylinders have been detected.

I suspect this is because your coordinates are not defined correctly or missing.
your best bet would be to add some print statements around this region.
```c
float xmin = coords[0];
	float xmax = coords[1];
	float ymin = coords[2];
	float ymax = coords[3];
	float lmin = 2.25; //assuming 3m slice
	float stepcovmax = 0.2;
	float radratiomin = 0.8;
	for(int i=0;i<regions.size();i++)
	{
		cylinder cyl;
		fitCylinder(regions[i],nnearest,true,true,cyl);
		if(cyl.ismodel == true)
		{		
			if(cyl.rad*2 >= dmin && cyl.rad*2 <= dmax && cyl.len >= lmin)
			{
				if(cyl.stepcov <= stepcovmax && cyl.radratio > radratiomin)
				{
					if(cyl.x >= xmin && cyl.x <= xmax)
					{
						if(cyl.y >= ymin && cyl.y <= ymax)
						{
							cyls.push_back(cyl.inliers);
						}
					}
				}
			}
		}
	}
```

to determine what expected coordinates you are getting.

Alternatively if you build the source form my fork there is already some extra debugging prints, and an early implementation of multi threading.
Regards Tony
