### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by bj-neilson** [apburt/treeseg#21]
Hi,
I've read your paper which was fascinating and manage to install treeseg.  I have a .pcd file generated by Google Cartographer from lidar data generated in a tree orchard.
Please forgive my ignorance, but I'm a bit stuck for how to use your algorithms on my point cloud.  Do I execute commands from the ~/treeseg DIR where I installed the package? Do I need to run then in another environment?  I'm running in Ubuntu 18.04
Thanks heaps
Ben

**Comment by apburt** [comment]
Hi Ben,

Unfortunately there is not much usage documentation yet. So the first step is to get the DEM and z-slice through these data. Assuming you have a xyz PCD point cloud, you should be able to start from the getdemslice binary, e.g.,:

~/treeseg/build/getdemslice 2 3 6 mycloud.pcd

Which will create a DEM from 2 metre slices, and the slice from 3-6m height.

Prior to this you may wish to downsample the point cloud, e.g.,

~/treeseg/build/downsample 0.04 mycloud.pcd

Would downsample your point cloud using a voxel grid with an edge length of 0.04m

Cheers,

Andy

**Comment by Jaqen-H-ghar** [comment]
Hi,
I saw tons of concept about DEM, but I still confused about three parameters of getdemslice,

can I please ask if get DEM slice is used to remove ground and findstem?if the tree is not that tall, how to decide the height of DEM? should the height include the crown, and if the first parameter '2' means the start position in z-axis.

Thanks!

**Comment by apburt** [comment]
Hi apologies for the delay - please see my response to #34, which includes a definition of the getdemslice parameters.
