### ISSUE TITLE
Parameters to tweek for crown segmentation

### ISSUE THREAD

**Issue by JulFrey** [apburt/treeseg#25]
Thank you for publishing this nice piece of software, I am triing to segment a forest patch with beech trees, scanned leafs-off, with a Rigel VZ400. Most parts of the algorithem work well untill the point of crown segmentation `segmentcrown [14 - 16] 0 ../beech.volume.*.pcd`. The results show strongly undersegmented crowns for all trees. Do you have any hint how to obtain a stronger segmentation? I already found out that the second parameter of the function turns on wood-leaf-segemntation but what is the first one '[14 - 16]' doing? Thanks for your help!
![beech21](https://user-images.githubusercontent.com/45684330/92374646-506f8000-f100-11ea-9d9a-9962718baebc.PNG)

**Comment by tpet93** [comment]
The first parameter is smoothness, it is a single number not a range.

smoothness refers to the angle threshold between surface normals to join anew point onto an existing segment.

smoothness is the main variable to tune the segmentation in treeseg. I suspect Andy wrote it as [14-16] to encourage users try a range of values in that region.

I would suggest running at 14, then if results still look like shown reducing it further

**Comment by apburt** [comment]
Hi both, apologies for the slow response. Probably far too late now, but I've been tinkering with the regionSegmentation function recently. JulFrey - if you are not familar with region growing segmentation there is a good primer here: https://pcl.readthedocs.io/projects/tutorials/en/latest/region_growing_segmentation.html. The newer tweaks consider consider a larger neighbourhood of points, than the version you were using. If you are using high-quality VZ-400 data, then I would suggest trying a value in the region of 5. This should do a better job of breaking the cloud into its underlying surfaces than it did in your image.

I hope to have some better documentation and a tutorial up this month.

Cheers,

Andy
