### ISSUE TITLE
PCL incompatibility

### ISSUE THREAD

**Issue by dalap125** [apburt/treeseg#26]
Hi,

First, of all, I'd like to thank you for developing and sharing your work! I'm very much looking forward to trying treeseg out! Unfortunately, I'm having some issues getting started. I followed the instructions on the main page, but there appears to be an incompatibility with the latest PCL library. When I run cmake, I get this error:

CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a configuration file for package "PCL" that is compatible
  with requested version "1.9".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake, version: 1.8.1

Any ideas?

Thank you very much!

**Comment by tpet93** [comment]
seems like you have installed pcl 1.8.1 instead of 1.9 or greater ?
you may need to install pcl from another source to get a newer version

**Comment by dalap125** [comment]
Hi,

Sorry, the ubuntu on my virtual machine wasn't compatible with the more recent PCL libraries.

Thank you very much!
