### ISSUE TITLE
how to test my data

### ISSUE THREAD

**Issue by wujilingfeng** [apburt/treeseg#31]
I have a PCD format file and want to test it,But the program named getdemslice run failed.I want to know what the four parameters means? How to test my data?

**Comment by Jaqen-H-ghar** [comment]
hi，
 
You can check an answer the author mentioned in the question [#21](https://github.com/apburt/treeseg/issues/21),

**Comment by apburt** [comment]
Hi both - I hope to have documentation and a tutorial up this month. But in the meantime, see my response to #34, which includes a definition of the getdemslice parameters.

**Comment by davodogster** [comment]
Looking forward to the tutorial/documentation! @apburt. Am currently Using the Wang2020 SSSC method (GUI) which is giving pretty good results on our dense lidar of the forest, but wanted to compare it with treeseg which sounds also promising :)
