### ISSUE TITLE
How long time do you guys nomally run with your own data?

### ISSUE THREAD

**Issue by Jaqen-H-ghar** [apburt/treeseg#32]
I'm running it with the command "./findstems 16 0.2 2 cloud.pcd cloud.pcd"
size of cloud.pcd is 369.1 kB, about 10000 cloud point.

the process is as followed:

Reading slice: complete
Cluster extraction: cloud.intermediate.slice.clusters.pcd | 1
Region-based segmentation: cloud.intermediate.slice.cluster.regions.pcd | 5
RANSAC cylinder fits:

and it keeps running for about 5 hours and is still running now.
am I doing something wrong? or it's slow because I'm running it using CPU r75800X.
I'll be really grateful if someone could answer me.

Jayla

**Comment by tpet93** [comment]
Certain steps can take a considerable amount of time.
However the RANSAC shouldn't take extremely long from memory, It seems you have only found 5 regions in your slice. 
Have you got less than 5 trees in your data?
This number should normally be greater than the number of trees your have in your data.

What may be happening is that: In your your slice, there has grown some very large regions and these very large regions may take a very long time to finish.

You should inspect cloud.intermediate.slice.cluster.regions.pcd to make sure each color (region) contains only one section of a stem. If stems are connected by ground/branches/vines you will need to adjust the height that the slice is taken at or change the smoothness value (first argument).

it should look similar to this 
![image](https://user-images.githubusercontent.com/26135231/104580822-7954e280-56a9-11eb-94ae-914d8ab615ad.png)

**Comment by Jaqen-H-ghar** [comment]
Thanks for your answer!

My original .pcd data only contains around 10 trees, which are cut from a large park scene. I think the reason I run it slowly is that cloud.intermediate.slice.cluster.regions.pcd file shows relatively discrete points, not as same as yours are clear stems, which means my original data is not good enough to do segmentation. 

I'm wondering if it's convenient for you to share your .pcd file with me?  Really appreciate your help. 

Regards

**Comment by tpet93** [comment]
More discrete points are normal,  the image above was just to illustrate the separated-ness of the stems.
You could try adding some extra prints (std::cout << "done:"<< i <<std::endl;) to the stem finding loop, This wont make it any faster but adds some mental reassurance that things are moving. 

You could also lower the number of max iterations:
treeseg.cpp:429		seg.setMaxIterations(1000000);
to 10,000.

This number controls how many attempts the RANSAC algorithim attempts before deciding it has found the best possible cylinder fit.

This will slightly reduce the chance that a good match will be found for each stem,(ie some trees may be missed) but will greatly reduce the maximum possible time spent per tree.

note. In this context, cylinder fitting refers to "finding stems" not volumetric models such as the ones produced by TreeQSM

Regards Tony

**Comment by Jaqen-H-ghar** [comment]
Hi Tony,
Thanks for your advice! I've added print code and set MaxIterations lower to 10000, but it still stuck on the same place for hours:

zsq@qingshan-zsq:~/Downloads/treeseg-0.2.0/build2$ ./findstems 15 0.2 2 kloud.slice.pcd kloud.slice.pcd
Reading slice: complete
Cluster extraction: kloud.intermediate.slice.clusters.pcd | 2
Region-based segmentation: kloud.intermediate.slice.clusters.regions.pcd | 5
RANSAC cylinder fits: 

the prior step is:
zsq@qingshan-zsq:~/Downloads/treeseg-0.2.0/build2$ ./getdemslice 2 0.5 5  kloud.tile.downsample.kloud.pcd
-27.4909 -19.0517 3.5466
-27.4909 -17.0517 0.444468
-27.4909 -15.0517 -0.294579
-27.4909 -13.0517 1.78738
-27.4909 -11.0517 3.40282e+38
-27.4909 -9.05169 3.40282e+38
........(omitted)

I did as you said slightly change the slice shorter by changing second and third parameters to make each color only contains one stem as much as possible, what does first parameter mean? does it affect much on segmentation?

Another problem I'm confusing, Andy used ../FGC01_coords.dat as the fourth parameter in the command:
findstems 5 0.2 2 ../FGC01_coords.dat ../FGC01.slice.pcd
but I'm using kloud.slice.pcd, which only contains three parameters in a line, the source code in findstems.cpp need four parameters a line:
```
        std::ifstream coordfile;
	coordfile.open(argv[4]);
	float coords[4];
	int n = 0;
	if(coordfile.is_open())
	{
		while(!coordfile.eof())
		{
			coordfile >> coords[n];
			n++;
		}
	}
	coordfile.close();
	float xmin = coords[0];
	float xmax = coords[1];
	float ymin = coords[2];
	float ymax = coords[3];

```
I've seen the answer you wrote in [question 16](https://github.com/apburt/treeseg/issues/16), but still not sure about how to use .pcd file in this command. 

Could you please give me some guides, many thanks!

Regards,
Jayla

**Comment by apburt** [comment]
Hi Jayla,

Apologies for the delay - I've just replied to #33 so I'm assuming this is now fixed. Feel free to reopen if not.

Cheers,

Andy
