### ISSUE TITLE
LAS to PCD then std::invalid_argument error

### ISSUE THREAD

**Issue by davodogster** [apburt/treeseg#34]
Hi guys, @apburt 

I have .las data that i can viz in cloudcompare. When I Run getdemslice I run into this error:
I had .las and exported it in CC as .pcd

![image](https://user-images.githubusercontent.com/46079516/106411604-87c53b80-64aa-11eb-9a34-dbe5178a8823.png)

Cheers,
Sam

**Comment by apburt** [comment]
Hi Sam,

My first guess would be that this is do with the file name. The permitted naming convention is currently very inflexible (see getFileID in treeseg.cpp).

I think this should work:

Nursery_6000pt_Nurstrial17_combined_crop1.tile.1.pcd 

Also getdemslice has 5 inputs (see getdemslice.cpp). The purpose of the binary is to load the point cloud, fit a DEM, and then generate and output a slice, along the z-axis, of the input cloud. The four parameters: 1) the resolution of the DEM in metres, 2) the percentile which is considered to constitute the ground (i.e., if all the points inside each DEM tile are lined up by their z coordinate - the point closest to the Nth percentile is considered the ground - sometimes useful for noisy data). 3)&4) The zmin and zmax of the slice. So e.g.,:

getdemslice 2 3 3 6 Nursery_6000pt_Nurstrial17_combined_crop1.tile.1.pcd 

This month I am going to try and put together some documentation as I'm aware it is sorely missing!

Hope this helps,

Cheers,

Andy

**Comment by davodogster** [comment]
Hi Andy @apburt thanks for your prompt reply,

It appears that I was getting the error because I was missing a parameter. I have renamed the file and added the extra param and it tries to execute because it pauses for 6 seconds before throwing the segmentation fault error.

![image](https://user-images.githubusercontent.com/46079516/106528048-f8bd2f80-654c-11eb-9b48-2dba87894d95.png)

(I already removed the ground in cloud compare and it's on a flat surface so I probably need to use another command and not DEMSLICE)

Cheers,
Sam

**Comment by apburt** [comment]
Hi - it's difficult to diagnose what is happening here, but the input is expected to be a larger-area point cloud (either a single tile, or many if a large dataset (e.g., > 4GB) - mydata.tile.*.pcd). I you want you can send me the data - I'm happy to take a quick look.

**Comment by davodogster** [comment]
Hi Andy, I'll ask my manager if I can send through the data. Should be okay. I sent you an email about using docker. It's strange because downsample worked and stored the output on my machine, but then I pulled the latest version of treeseg last week and downsample still seems to run but it's no outputting anything anymore. Really looking forward to the rest of the tutorial documentation aswell! I understand that a special REIGL account is needed if people want to use your data for the tutorial?

**Comment by apburt** [comment]
Apologies for the long delay - the tutorial has now been completed and the preprocessed tutorial data (i.e., does not require the rivlib libraries etc) are available at https://zenodo.org/record/4661301. Hope this all helps. Cheers, Andy
