### ISSUE TITLE
Can you provide an example.pcd?

### ISSUE THREAD

**Issue by XGL96** [apburt/treeseg#36]
Because I failed to download riegl, I directly used my own pcd data, and the commands I tired were
```
../downsample 0.04 part_small.pcd
../getdemslice 2 3 0 3 part_small.tile.downsample.part_small.pcd
../findstems 15 0.2 2 nouragesH20_coords.dat part_small.slice.pcd
```
where *part_small.pcd* was my data, and in nouragesH20_coords.dat I set
```
-100 100 -100 100
```
to allow all points in the region.

But no cylinder was found, so I wonder if there is something wrong with my usage somewhere, or maybe it is because the stem is too short in my data and ransac cannot raise enough points belonging to the columns.

So please can you give an example of pcd and the command, and let me make a try/ learn how to use?

**Comment by apburt** [comment]
Hi - ok yes I'll upload the data used in the tutorial in pcd format, so as to skip the first preprocessing step - I'll try and get this done in the next couple of weeks.

Cheers,

Andy

**Comment by XGL96** [comment]
Thanks, I will look forward to it.

**Comment by apburt** [comment]
Hi - the preprocessed data (i.e., co-registered, some noise removal and in PCD format) used in the treeseg tutorial (which is still being written up), are now available here: https://zenodo.org/record/4661301
