### ISSUE TITLE
Trouble installing.

### ISSUE THREAD

**Issue by jonaselmesten** [apburt/treeseg#37]
Hello!

Everything builds correctly (seemingly), but  I just get "command not found" when trying the different commandos. 
Where can I find the relevant arguments for each commando? Because I can run the executable and it works, but I don't know the arguments for stem segmentation (documentation not available), so I'm stuck on this part.

Thank you.

**Comment by apburt** [comment]
Hi,

On the first part: you'll need to update the environment variable PATH to include the the directory containing the built executables. The readme now contains a section on this.

The second part: the tutorial has still not yet been completely written - but I have added ./doc/tutorial_tldr.md, which shows how to call the commands.

Cheers,

Andy
