### ISSUE TITLE
Missing file: ../matrix/

### ISSUE THREAD

**Issue by chaofeng2007** [apburt/treeseg#4]

**Comment by apburt** [comment]
Think this is solved now, but for info:

rxp2pcd (whose purpose is to convert N scans into a larger-area point cloud in .pcd format) requires RIEGL VZ-400 data in 'raw' form (i.e., straight of the scanner). E.g.,:

-YYYY-MM-DD.XXX.riproject
--ScanPos001
---YYMMDD_HHMMSS.rxp etc.
--ScanPos002
--ScanPos003

If working inside of this directory, then the two folders: matrix and extraction are to be made. Inside matrix are the co-registration matrices (4x4, ASCII), generated using RiSCAN Pro, to convert each scan into the coordinate system of Scan001. Then rxp2pcd can be run as:

```
cd extraction;
rxp2pcd ../ plot_coords.dat 60 15 plotID;  
```

Where 60 and 15 denote tiling size and deviation filter threshold respectively. And plot_coords.dat have been derived from the plotcoords binary.

Better documentation is required. Is on the to-do list!
