### ISSUE TITLE
error: 'split' is not a member of 'boost'

### ISSUE THREAD

**Issue by seththefirst** [apburt/treeseg#46]
Hi Guys, so I'm trying to build the project, and I'm getting an error with the boost library.
Seems like my version of the boost library is wrong.
Where can I check the correct version, please ?

`roberto@roberto-VirtualBox:~/treeseg/build$ make
Consolidate compiler generated dependencies of target treeseg
[  3%] Building CXX object CMakeFiles/treeseg.dir/src/treeseg.cpp.o
/home/roberto/treeseg/src/treeseg.cpp: In function ‘std::vector<std::__cxx11::basic_string<char> > getFileID(std::string)’:
/home/roberto/treeseg/src/treeseg.cpp:54:16: error: ‘split’ is not a member of ‘boost’
   54 |         boost::split(tmp1,filename,boost::is_any_of("/"));
      |                ^~~~~
/home/roberto/treeseg/src/treeseg.cpp:55:16: error: ‘split’ is not a member of ‘boost’
   55 |         boost::split(tmp2,tmp1[tmp1.size()-1],boost::is_any_of("."));
      |                ^~~~~
/home/roberto/treeseg/src/treeseg.cpp: In function ‘void readTiles(const std::vector<std::__cxx11::basic_string<char> >&, pcl::PointCloud<PointTreeseg>::Ptr&)’:
/home/roberto/treeseg/src/treeseg.cpp:83:24: error: ‘split’ is not a member of ‘boost’
   83 |                 boost::split(tmp1,filename,boost::is_any_of("/"));
      |                        ^~~~~
/home/roberto/treeseg/src/treeseg.cpp:84:24: error: ‘split’ is not a member of ‘boost’
   84 |                 boost::split(tmp2,tmp1[tmp1.size()-1],boost::is_any_of("."));
      |                        ^~~~~
/home/roberto/treeseg/src/treeseg.cpp: In function ‘int getTilesStartIdx(const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/roberto/treeseg/src/treeseg.cpp:104:24: error: ‘split’ is not a member of ‘boost’
  104 |                 boost::split(tmp1,filename,boost::is_any_of("/"));
      |                        ^~~~~
/home/roberto/treeseg/src/treeseg.cpp:105:24: error: ‘split’ is not a member of ‘boost’
  105 |                 boost::split(tmp2,tmp1[tmp1.size()-1],boost::is_any_of("."));
      |                        ^~~~~
make[2]: *** [CMakeFiles/treeseg.dir/build.make:76: CMakeFiles/treeseg.dir/src/treeseg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/treeseg.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

`

**Comment by seththefirst** [comment]
I was using the wrong ubuntu version.

**Comment by andeyeluguo** [comment]
在相应位置加上这个
#include <boost/algorithm/string.hpp>
跟ubuntu版本关系不大

**Comment by CiSong10** [comment]
> 在相应位置加上这个 #include <boost/algorithm/string.hpp> 跟ubuntu版本关系不大

This helps. 我通过这个解决了
