### ISSUE TITLE
treeseg needs newer armadillo than is available on xenial

### ISSUE THREAD

**Issue by jgrn307** [apburt/treeseg#5]
Andy: can you perhaps mod the README to note what version of armadillo you are recommending?  We found that the version of armadillo that is available via Ubuntu xenial wasn't sufficient (6.5) -- Ubuntu bionic worked to compile, however (8.4).  I think you need 7.960 or later?  When they introduced gmm_full?  http://arma.sourceforge.net/docs.html#api_additions

Thanks!

**Comment by apburt** [comment]
Fixed via #3 and readme updated to include min dependancy versions. Thanks!

**Comment by jgrn307** [comment]
Andrew, the page still lists Ubuntu 16.04 (xenial, which does not have the right version of libarmadillo): https://packages.ubuntu.com/xenial/libarmadillo-dev

Can you tweak to suggest Ubuntu 18.04 (bionic) or later?
