### ISSUE TITLE
downsample: command not found

### ISSUE THREAD

**Issue by Knutchanat** [apburt/treeseg#50]
I'm so confused. What I do wrong? I'm trying to use downsample command but it respond not found.
![image](https://user-images.githubusercontent.com/105915722/224874045-8631835e-9026-4445-a086-aeab6af415f9.png)
![image](https://user-images.githubusercontent.com/105915722/224874335-e3b4d49f-5263-405c-b301-6f62e736493c.png)

**Comment by tim-devereux** [comment]
If the binary is not added to your system path you will have to run it using ./downsample

FYI If you are wanting to segment trees from TLS, these libraries are being actively maintained.

https://github.com/csiro-robotics/raycloudtools
https://github.com/philwilkes/TLS2trees

**Comment by Knutchanat** [comment]
Thankyou so much for your information.
