### ISSUE TITLE
Formal request: LAS "starting point"

### ISSUE THREAD

**Issue by jgrn307** [apburt/treeseg#6]
Andy (sorry for the barrage of stuff, I'm trying to document our issues using treeseg right now) -- I'd like to formally request .LAS support at least as a starting point.  We aren't starting with the raw RIEGL data (as we discussed, the 400i seems to have a different format than you guys had).  I think a more "stable" starting point would be some standard point cloud format like LAS, which then can get converted to PCD (and probably needs tiling support built in).  We have a starting point from:

https://github.com/murtiad/las2pcd

And I've made an ubuntu-ready (plus allows input files as a parameter rather than needing interactive) at:

https://github.com/gearslaboratory/las2pcd

**Comment by jgrn307** [comment]
Just as a note, we got ahold of a backpack lidar we wanted to try your software out on, and it is not RIEGL in any way!

**Comment by apburt** [comment]
Hi Jonathan, yes noted and will have a got at it as soon as possible. Will leave issue open until sorted.

**Comment by jgrn307** [comment]
I made this comment in another thread, but a solution if you have PDAL installed with the appropriate drivers (minimally PCL, but for us the LAS drivers as well), you can do the conversion and downsampling from any point cloud format PDAL can read (https://pdal.io/stages/readers.html) via:

```
LEAF_SIZE="0.04" 
INPUT="some.las"
OUTPUTBASE="some"
pdal translate \
	-v 4 \
	--writers.pcd.xyz=true \
	-i $INPUT \
	-o $OUTPUTBASE".pcd" \
	voxelgrid \
	--filters.voxelgrid.leaf_x=$LEAF_SIZE \
	--filters.voxelgrid.leaf_y=$LEAF_SIZE \
	--filters.voxelgrid.leaf_z=$LEAF_SIZE
```
Where the LEAF_SIZE parameter is the voxel size in point cloud units.  -i and -o need the appropriate file extensions (e.g. .las and .pcd) to trigger the correct read/write.

**Comment by apburt** [comment]
I'm going to go ahead and close this one for now - the expected starting point of the current version is tiled pcd files. As mentioned at the top of the issue there are now quite a few tools available for converting las to pcd. I think it should be up to the user to do the conversion, as it may be desirable to carry across additional attributes (e.g., reflectance), which is now feasible since PointTreeseg has been implemented (treeseg_pointtype.h).
