### ISSUE TITLE
writer.write error and fix -- use ASCII output instead of binary

### ISSUE THREAD

**Issue by jgrn307** [apburt/treeseg#7]
We found one of the issue we were having was with the writer.write statement.  It looks like the binary format invokes mmap which can be problematic on different systems.  By modifying the final parameter to be "false" (ASCII) instead of "true" (binary) throughout the code, we were able to get some of the steps working properly, e.g.:

writer.write(ss.str(),*cloud,false);

This issue was reported elsewhere on the PCL sites.

**Comment by apburt** [comment]
Ok thanks - noted, will output in ASCII by default and optionally as binary via a flag. Leaving open until done.

**Comment by apburt** [comment]
I'm going to close this also as going forward the master will only be tested on Ubuntu and Red Hat, and outputting in binary is desirable.

This def might be useful to note for anyone building on other systems.
