### ISSUE TITLE
PCD format -- possible solution to our woes...

### ISSUE THREAD

**Issue by jgrn307** [apburt/treeseg#8]
Ok, at long last we think we figured out what was happening to our analysis.  The TLS points were in CA Teale Albers, which are VERY large numbers (projected, meter-based system) which we think were leading to numerical overflow errors.

We were able to properly create a working PCD file using pdal translate via the singularity container you can grab at:
singularity pull shub://gearslaboratory/gears-singularity:gears-pdal

This container is converter from the docker file: msmitherdc/pdal:1.7 (which you could also use).  Note PDAL is a giant pain to compile from scratch.

singularity exec ~/gearslaboratory-gears-singularity-master-gears-pdal.simg pdal translate \
	--writers.pcd.xyz=true \
	P002_E1_clip_fixed.las \
	P002_E1_clip_fixed.pcd \
	-v 4

There's a couple of keys here that I think allowed this to work.  First, the .xyz=true is neccessary to avoid RGB errors (also, treeseg doesn't use RGB).

Second, an important default for this conversion (https://pdal.io/stages/writers.pcd.html) is the subtract_minimum=true, which calculates the point cloud min x,y,z and simply subtracts that from every point.  Our plots are only 30m, so the true range is pretty small, but the actual numbers were gigantic.

This seems to work great.  As a bonus, you can skip "downsample" and use this command to both convert and voxelize:

singularity exec ~/gearslaboratory-gears-singularity-master-gears-pdal.simg pdal translate \
	--writers.pcd.xyz=true \
	-i P002_E1_clip_fixed.las \
	-o P002_E1_clip_fixed_voxel04.pcd \
	voxelgrid \
	--filters.voxelgrid.leaf_x="0.04" \
	--filters.voxelgrid.leaf_y="0.04" \
	--filters.voxelgrid.leaf_z="0.04"

This is identical to downsample's voxel algorithm (both use PCL).

So, in the short term I think we have it working via the PDAL translate.  It might be worth some tweaks down the line to your rxp2pcd and txt2pcd for these weird projections tho!

**Comment by davodogster** [comment]
I'm keen to give something like this a try. My forest Lidar is currently in .LAZ format, what would you recommend? @jgrn307 @apburt

**Comment by apburt** [comment]
Closing this for now (see #6). But thanks for the useful information for those using las format.
